#!/bin/bash

function b_log() {
    tput bold & tput setaf 7

    read -e -r -p "how many previous commits would you like to see?: " numcommits

    if [[ $numcommits == "" ]]; then
        numcommits=6
    fi

    commitarray=($(git log -$numcommits | grep commit | sed 's/commit//g'))
    verbosecommits=$(git shortlog -$numcommits --reverse | sed 1d);

    for ((i = 0; i < numcommits; i++)) do
        j=$(echo ${i} + 1 | bc)
        nextcommit=$(echo "${verbosecommits}" | head -n $j | tail -n 1)
        echo -e "  ${i}) ${commitarray[$i]}${nextcommit}"
    done

    exit 0
}
