#!/bin/bash

function b_revert() {
    read -e -r -p "would you like to revert back to a previous commit?: " revert
    tput bold & tput setaf 7
    if [[ $revert == "y" || $revert == "yes" ]] ; then

        read -e -r -p "how many previous commits would you like to see?: " numcommits
        if [[ $numcommits == "" ]]; then
            numcommits=6
        fi

        commitarray=($(git log -$numcommits | grep commit | sed 's/commit//g'))
        verbosecommits=$(git shortlog -$numcommits --reverse | sed 1d);

        for ((i = 0; i < numcommits; i++)) do
            j=$(echo ${i} + 1 | bc)
            nextcommit=$(echo "${verbosecommits}" | head -n $j | tail -n 1)
            echo -e "  ${i}) ${commitarray[$i]}${nextcommit}"
        done
        read -e -r -p "choose commit to revert back to: " version
        echo "reverting back to version: ${commitarray[$version]}"
        git reset --hard ${commitarray[$version]}
        for ((i = 0; i < numrepos; i++)) ; do
            git push --force ${remotearray[i]} > /dev/null 2>&1 ;
        done
        exit 0
    else
        echo -e "no revisions to git branch have been made."
    fi
}
